### PR TITLE
Clippy fixes

### PR DESCRIPTION
**Pull request by cwlittle**

### CODE REVIEW

**Comment by cwlittle** [comment]
@mappum I'll need a bit of help getting the safety sections written out for detach and detach_expect in src/tree/walk/mod.rs. I tried to remove the unsafe in the function definition to see the location of the unsafe lines in detach to get a bit more context, but it looks like this is unsafe for some reason beyond that. It's still a bit arcane to me.

**Comment by cwlittle** [comment]
Although, it looks like the result that triggers a clippy failure is only an error. In our case, it was the drop rather than ManuallyDrop::drop that wasn't dropping the inner value. Clippy is passing with just warnings. We could leave these safety blocks until we revisit documentation. In any case, keeping clippy clean in merk will be much easier now that we have less of a wall to deal with.

**Review by mappum — APPROVED** [review]
Checked out all the changes, all looks good. Impressed at some of the things clippy can pick up, and I guess I'll also have to incorporate `matches!()` into my repertoire.

**Comment by mappum** [comment]
Also removed the `unsafe` markers from those 2 methods, since it was overkill anyway. It was just there to mark that modifying the tree could result in a weird state if you forget to finalize it (e.g. recomputing hashes), but the tree API is a low-level internal API so I don't think we have to make that so explicit.

**Pull request merged**
